### ISSUE TITLE
Replace kcat with kafka scipts within probes

### ISSUE THREAD

**Issue by Maleware** [stackabletech/kafka-operator#454]
With multi-arch we'd have to host and maintain kcat on our own. Therefore we replace kcat with kafka scripts and get rid of this dependency.

**Comment by teozkr** [comment]
We used to do this, but moved away because of the ridiculous CPU overhead from starting a new Java Kafka client every time.

**Comment by maltesander** [comment]
Yeah i saw it during implementation / testing... i will try with curl now

**Comment by teozkr** [comment]
Can't we just bundle kcat into our Kafka images?

**Comment by maltesander** [comment]
We want to get rid of 3rd party dependencies for multi arch builds. @Maleware mentioned we would need to maintain our own build for kcat arm etc.

**Comment by maltesander** [comment]
Closing for now. We need another approach than just using the kafka provided java scripts which are way too cpu intensive.
