### ISSUE TITLE
Prototype: More welcoming README!

### ISSUE THREAD

**Issue by fhennig** [stackabletech/kafka-operator#480]
We want to have a more polished Readme inviting users to interact with the Stackable Universe!

To figure out what a good readme looks like for all operators, we will spike it in the secret-operator and in the kafka-operator.

The point is to experiment, and see what content we want, to later make sure we can template a similar layout for all operators.

Inspiration of good READMEs which we could try to imitate: [ChrunchyData/postgres-operator](https://github.com/CrunchyData/postgres-operator), [datahub-project/datahub](https://github.com/datahub-project/datahub)

It could make sense to spike multiple README versions and get feedback.

## Ideas (not requirements)

- **connect to user intentions when they visit the readme**
    - find out what the tool is
    - no-nonsense information for technical users, what does it _do_
        - It reads a CR and creates XYZ
    - is the tool well maintained and reliable?
        - make it professional and a bit flashy (the company logo is a good signal)
- it should be visual, not a wall of text
    - maybe a gif of an install?
- maybe a diagram?
    - maybe this one? https://stackable.tech/wp-content/uploads/2022/06/illustration-40.jpg
- show that the operator is part of a larger platform and integrates well with the other operators (i.e. kafka needs a zookeeper and the SDP includes a zookeeper operator)
    - list all operators?
- this is not for you if ...
- Quickstart
    - stackablectl
- which flavors of k8s do we support (k3s, managed k8s, Openshift (soon))
- Contributing
- link to blog posts if it makes sense
- (companies that use the product)

## Required Content (by topic, not necessarily by title)

The new README version should contain information/sections about:

- Introduction
- Quickstart (stackablectl)
- Technical no-nonsense how does it work
- About the Stackable Data Platform
- List of other operators
- Contributing
- Further Reading

## Acceptance Criteria

- [x] Created at least one new file called README_v1.md with above content.
- [x] The actual content of the sections does not need to be polished or final. Think one step above lorem ipsum.
- [x] The new README can incorporate information of the existing README.md, as well as the new required sections in a nice flow
- [x] You MAY jot down considerations of how the new README could be recreated using templating techniques for future tasks

**Comment by vsupalov** [comment]
You can view a rendered version of the README draft [here](https://github.com/stackabletech/kafka-operator/blob/prototype-readme/README_v1.md).

We can use the [PR](https://github.com/stackabletech/kafka-operator/pull/483) to discuss details.

**Comment by fhennig** [comment]
We've gathered some feedback and can now continue work on the next ticket in the epic

**Comment by lfrancke** [comment]
I like it!
