### ISSUE TITLE
Service exposition with ListenerClasses

### ISSUE THREAD

**Issue by Jimvin** [stackabletech/kafka-operator#714]
The Stackable Kafka operator currently does not support managing service exposition with ListenerClasses in the way that other Stackable operators do. There are use cases when keeping Kafka listeners internal to the cluster makes sense, so implementing this as it has been done for other components in the stack would be useful.

**Comment by soenkeliebau** [comment]
Stale PR for this here: https://github.com/stackabletech/kafka-operator/pull/443/files

**Comment by nightkr** [comment]
This has a few followup tasks for list-op:

- https://github.com/stackabletech/listener-operator/issues/220
- https://github.com/stackabletech/listener-operator/issues/221
- https://github.com/stackabletech/listener-operator/issues/229

**Comment by nightkr** [comment]
Release notes:

> # New/extended platform features
> 
> The Stackable Operator for Kafka now uses the Stackable Listener Operator, allowing connectivity to be customized.
> 
> # Breaking changes
> 
> The existing services will be migrated to the new format. Clients will need to re-read settings from the discovery configmap after upgrading.
> 
> Kafka is now only accessible from within the Kubernetes cluster by default. A listener class must be configured manually to expose it to the outside world.
> 
> To complete the upgrade, all existing Kafka StatefulSets must be deleted manually (they will be recreated by the operator). Kafka will be unavailable until this is done.

**Comment by lfrancke** [comment]
Thank you very much for the release notes. Does this also have docs we can link to?

**Comment by nightkr** [comment]
Yes, https://docs.stackable.tech/home/nightly/kafka/usage-guide/listenerclass.
